/* action types */

// Temp
export const GET_EXPERIENCES = 'GET_EXPERIENCES'
export const GET_EXPERIENCES_SUCCESS = 'GET_EXPERIENCES_SUCCESS'
export const GET_EXPERIENCES_FAILURE = 'GET_EXPERIENCES_FAILURE'

